# gradle/libs.versions.toml
[versions]
kotlin = "2.2.21"
arrow = "2.1.2"
ksp = "2.3.3"
kotlinSerialization = "1.9.0"
kotlinPoet = "1.15.0"

[plugins]
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }

[libraries]
arrow-core = { module = "io.arrow-kt:arrow-core", version.ref = "arrow" }
hnau-kotlin = { module = "com.github.hnau256.common-kotlin:common-kotlin", version = "1.5.0" }
hnau-gen-kt = { module = "com.github.hnau256.common-gen-kt:common-gen-kt", version = "1.3.0" }
ksp-api = { module = "com.google.devtools.ksp:symbol-processing-api", version.ref = "ksp" }
kotlin-serialization-core = { module = "org.jetbrains.kotlinx:kotlinx-serialization-core", version.ref = "kotlinSerialization" }
kotlinpoet-core = { module = "com.squareup:kotlinpoet", version.ref = "kotlinPoet" }
kotlinpoet-ksp = { module = "com.squareup:kotlinpoet-ksp", version.ref = "kotlinPoet" }